// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"github.com/oublie6/awesome-zero-platform/server/apps/app-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health/live",
				Handler: liveHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/health/ready",
				Handler: readyHandler(serverCtx),
			},
		},
	)
}
