<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';import { ElMessage, ElMessageBox } from 'element-plus';import PageHeader from '@/components/PageHeader.vue';import CodePanel from '@/components/CodePanel.vue';import { adminApi } from '@/api/admin';import type { Permission, Resource, Role } from '@/types/admin'
const roles=ref<Role[]>([]),resources=ref<Resource[]>([]),selected=ref<Role|null>(null),permissions=ref<Permission[]>([]),dialog=ref(false),editing=ref<Role|null>(null);const form=reactive({code:'',displayName:'',description:''})
async function load(){[roles.value,resources.value]=await Promise.all([adminApi.roles(),adminApi.resources()]);if(!selected.value&&roles.value[0])await select(roles.value[0])}
async function select(role:Role){selected.value=role;permissions.value=await adminApi.rolePermissions(role.code)}
function checked(resource:string,action:string){return permissions.value.some(p=>p.resource===resource&&p.action===action)}
function toggle(resource:string,action:string,value:boolean){const next=permissions.value.filter(p=>!(p.resource===resource&&p.action===action));if(value)next.push({resource,action});permissions.value=next}
async function savePermissions(){if(!selected.value)return;await adminApi.replaceRolePermissions(selected.value.code,permissions.value);ElMessage.success('权限已保存')}
function open(role?:Role){editing.value=role||null;Object.assign(form,role||{code:'',displayName:'',description:''});dialog.value=true}
async function save(){if(editing.value)await adminApi.updateRole(editing.value.code,form);else await adminApi.createRole(form);dialog.value=false;await load();ElMessage.success('角色已保存')}
async function remove(role:Role){await ElMessageBox.confirm(`删除角色 ${role.displayName}？该角色必须没有成员。`,'危险操作');await adminApi.deleteRole(role.code);selected.value=null;await load()}
const rawPreview=()=>permissions.value.map(p=>`p, ${selected.value?.code}, ${p.resource}, ${p.action}`).join('\n')
onMounted(load)
</script>
<template><PageHeader title="角色管理" description="角色信息、资源操作矩阵和最终生成的 Casbin p 策略放在同一个工作区。"><el-button type="primary" @click="open()">创建角色</el-button></PageHeader><div class="role-grid"><section class="panel role-list"><div v-for="role in roles" :key="role.code" :class="['role-item',{active:selected?.code===role.code}]" @click="select(role)"><div><b>{{role.displayName}}</b><small>{{role.code}}</small></div><el-tag v-if="role.system" size="small">SYSTEM</el-tag></div></section><section v-if="selected" class="panel"><div class="role-title"><div><h2>{{selected.displayName}}</h2><span class="technical muted">{{selected.code}}</span></div><div><el-button @click="open(selected)">编辑</el-button><el-button v-if="!selected.system" type="danger" plain @click="remove(selected)">删除</el-button></div></div><el-tabs><el-tab-pane label="权限矩阵"><el-table :data="resources"><el-table-column label="资源" min-width="230"><template #default="s"><b>{{s.row.displayName}}</b><div class="technical muted">{{s.row.pattern}}</div></template></el-table-column><el-table-column label="操作" min-width="420"><template #default="s"><el-checkbox v-for="action in s.row.actions" :key="action" :model-value="checked(s.row.pattern,action)" @change="v=>toggle(s.row.pattern,action,Boolean(v))"><span class="technical">{{action}}</span></el-checkbox></template></el-table-column></el-table><el-button type="primary" style="margin-top:16px" @click="savePermissions">保存权限</el-button></el-tab-pane><el-tab-pane label="原始策略"><CodePanel title="GENERATED CASBIN POLICY" :value="rawPreview()||'# no policy'"/></el-tab-pane><el-tab-pane label="技术信息"><el-descriptions :column="1" border><el-descriptions-item label="Role Code"><span class="technical">{{selected.code}}</span></el-descriptions-item><el-descriptions-item label="System Role">{{selected.system}}</el-descriptions-item><el-descriptions-item label="Created">{{selected.createdAt}}</el-descriptions-item></el-descriptions></el-tab-pane></el-tabs></section></div><el-dialog v-model="dialog" :title="editing?'编辑角色':'创建角色'"><el-form label-position="top"><el-form-item label="角色编码"><el-input v-model="form.code" :disabled="Boolean(editing)" placeholder="platform_operator"/></el-form-item><el-form-item label="显示名称"><el-input v-model="form.displayName"/></el-form-item><el-form-item label="描述"><el-input v-model="form.description" type="textarea"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog></template>
<style scoped>.role-grid{display:grid;grid-template-columns:300px 1fr;gap:16px}.role-list{padding:8px}.role-item{padding:14px;border-radius:8px;display:flex;align-items:center;justify-content:space-between;cursor:pointer}.role-item:hover,.role-item.active{background:#1b2b39}.role-item small{display:block;font:11px var(--az-mono);color:var(--az-muted);margin-top:5px}.role-title{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:12px}.role-title h2{margin:0}</style>
