<script setup lang="ts">
import { reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { useAuthStore } from '@/stores/auth'
const auth=useAuthStore(),router=useRouter(),route=useRoute(),loading=ref(false); const form=reactive({identifier:'',password:''})
async function submit(){loading.value=true;try{await auth.login(form.identifier,form.password);await router.replace(String(route.query.redirect||'/dashboard'))}catch(e){ElMessage.error(e instanceof Error?e.message:'登录失败')}finally{loading.value=false}}
</script>
<template><div class="auth-page"><section class="auth-visual"><div class="scanline"></div><div class="terminal"><span>AWESOME ZERO PLATFORM</span><h1>ADMIN<br/>CONTROL PLANE</h1><p>IDENTITY · AUTHORIZATION · OPERATIONS</p><div class="status">● SECURE CHANNEL READY</div></div></section><section class="auth-form"><el-form label-position="top" @submit.prevent="submit"><div class="kicker">AUTHORIZED PERSONNEL ONLY</div><h2>管理员登录</h2><p class="muted">使用用户名、邮箱或手机号登录平台控制面。</p><el-form-item label="身份标识"><el-input v-model="form.identifier" size="large" autocomplete="username" placeholder="username / email / phone"/></el-form-item><el-form-item label="密码"><el-input v-model="form.password" size="large" type="password" show-password autocomplete="current-password" @keyup.enter="submit"/></el-form-item><el-button type="primary" size="large" :loading="loading" style="width:100%" @click="submit">建立管理会话</el-button><el-button link style="width:100%;margin:14px 0 0" @click="router.push('/bootstrap')">首次部署？初始化超级管理员</el-button></el-form></section></div></template>
<style scoped>.auth-page{min-height:100vh;display:grid;grid-template-columns:1.4fr 1fr}.auth-visual{position:relative;display:flex;align-items:flex-end;padding:7vw;background:linear-gradient(135deg,#07101a,#0d1e2c 58%,#111827);overflow:hidden}.auth-visual:before{content:"";position:absolute;inset:0;background-image:linear-gradient(#38bdf811 1px,transparent 1px),linear-gradient(90deg,#38bdf811 1px,transparent 1px);background-size:44px 44px;mask-image:linear-gradient(to bottom,transparent,#000)}.terminal{position:relative}.terminal span,.terminal p,.status{font:12px var(--az-mono);letter-spacing:2px;color:#7dd3fc}.terminal h1{font:800 clamp(48px,7vw,104px)/.88 var(--az-mono);letter-spacing:-7px;margin:18px 0;color:#f1f7fd}.status{margin-top:50px;color:#4ade80}.auth-form{display:grid;place-items:center;padding:50px;background:#0c1219}.el-form{width:min(420px,100%)}.kicker{font:11px var(--az-mono);color:#fb7185;letter-spacing:1.5px}h2{font-size:32px;margin:12px 0 6px}.el-form-item{margin-top:25px}.scanline{position:absolute;inset:0;background:linear-gradient(transparent 50%,#00000018 50%);background-size:100% 4px;pointer-events:none}</style>
