<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue';import { ElMessage, ElMessageBox } from 'element-plus';import PageHeader from '@/components/PageHeader.vue';import CodePanel from '@/components/CodePanel.vue';import { adminApi } from '@/api/admin';import type { EngineInfo, Explanation, RawRule } from '@/types/admin'
const engine=ref<EngineInfo|null>(null),model=ref(''),rules=ref<RawRule[]>([]),text=ref(''),loading=ref(true),explanation=ref<Explanation|null>(null);const probe=reactive({subject:'',resource:'/admin/accounts',action:'GET'})
const policyText=computed(()=>rules.value.map(r=>[r.ptype,...r.values].join(', ')).join('\n'))
const capabilities=computed(()=>{if(!engine.value)return[];const e=engine.value;return [['raw-policy',e.supportsRawPolicy],['model-inspection',e.supportsModelInspection],['model-editing',e.supportsModelEditing],['policy-explanation',e.supportsPolicyExplanation],['batch-import',e.supportsBatchImport],['role-hierarchy',e.supportsRoleHierarchy]].filter(([,on])=>on).map(([name])=>String(name))})
function parsePolicy(input:string):RawRule[]{return input.split('\n').map(v=>v.trim()).filter(v=>v&&!v.startsWith('#')).map(line=>{const [ptype,...values]=line.split(',').map(v=>v.trim());return{ptype,values}})}
async function load(){loading.value=true;try{const [e,m,p]=await Promise.all([adminApi.engine(),adminApi.model(),adminApi.policies()]);engine.value=e;model.value=m.model;rules.value=p;text.value=p.map(r=>[r.ptype,...r.values].join(', ')).join('\n')}finally{loading.value=false}}
async function validate(){try{await adminApi.validatePolicies(parsePolicy(text.value));ElMessage.success('策略格式和平台保护规则校验通过')}catch(e){ElMessage.error(e instanceof Error?e.message:'校验失败')}}
async function save(){await ElMessageBox.confirm('这会整体替换当前权限引擎策略。系统将拒绝删除最后一个超级管理员或超级管理员通配规则。','高风险策略替换',{type:'warning',confirmButtonText:'替换策略'});await adminApi.replacePolicies(parsePolicy(text.value));ElMessage.success('策略已原子替换');await load()}
async function explain(){explanation.value=await adminApi.explain(probe)}
onMounted(load)
</script>
<template><PageHeader title="权限引擎" expert description="面向后端开发与安全管理员的插件原生工作台：查看 Casbin Model、编辑 p/g 策略并执行 Enforce 解释。"/><div class="expert-banner">HIGH IMPACT AREA — 所有写操作仍通过 Authz 插件接口执行，不直接修改 authorization_casbin_rules 表。</div><section v-if="engine" class="grid grid-4" style="margin-bottom:16px"><div class="panel"><div class="metric-label">ENGINE</div><div class="metric-value">{{engine.name}}</div></div><div class="panel"><div class="metric-label">ADAPTER</div><div class="metric-value" style="font-size:17px">{{engine.version}}</div></div><div class="panel"><div class="metric-label">MODEL</div><div class="metric-value" style="font-size:17px">{{engine.modelType}}</div></div><div class="panel"><div class="metric-label">RULES</div><div class="metric-value">{{rules.length}}</div></div></section><el-tabs v-loading="loading"><el-tab-pane label="模型"><CodePanel title="CASBIN MODEL (READ ONLY)" :value="model"/><div class="panel" style="margin-top:14px"><b>Capabilities</b><div style="margin-top:10px"><el-tag v-for="c in capabilities" :key="c" style="margin:4px"><span class="technical">{{c}}</span></el-tag></div></div></el-tab-pane><el-tab-pane label="原始策略"><div class="toolbar"><el-button @click="text=policyText">恢复已加载内容</el-button><el-button type="success" plain @click="validate">校验</el-button><el-button type="danger" @click="save">整体替换</el-button><span class="muted">支持 p、g；逗号分隔，每行一条。</span></div><el-input v-model="text" type="textarea" :rows="24" class="policy-editor" spellcheck="false"/></el-tab-pane><el-tab-pane label="Enforce 调试器"><div class="grid grid-2"><section class="panel"><el-form label-position="top"><el-form-item label="Subject"><el-input v-model="probe.subject" placeholder="account UUID"/></el-form-item><el-form-item label="Object"><el-input v-model="probe.resource"/></el-form-item><el-form-item label="Action"><el-input v-model="probe.action"/></el-form-item><el-button type="primary" @click="explain">执行并解释</el-button></el-form></section><section class="panel"><template v-if="explanation"><el-result :icon="explanation.allowed?'success':'error'" :title="explanation.allowed?'ALLOW':'DENY'" :sub-title="`${explanation.subject} → ${explanation.resource} [${explanation.action}]`"/><div><b>Roles</b><p class="technical">{{explanation.roles.join(', ')||'(none)'}}</p><b>Matched Rules</b><CodePanel :value="explanation.matchedRules.map(r=>[r.ptype,...r.values].join(', ')).join('\n')||'# no matching policy'"/></div></template><el-empty v-else description="输入请求三元组后执行"/></section></div></el-tab-pane></el-tabs></template>
<style scoped>.policy-editor:deep(textarea){font:13px/1.65 var(--az-mono);background:#080d13;color:#d7e1ec}</style>
